spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/habit
    username: postgres
    password: jiyjo@2001
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
        org:
          hibernate:
            SQL: DEBUG
            type:
              descriptor:
                sql:
                  BasicBinder: TRACE


##spring:
##  datasource:
##    url: jdbc:postgresql://localhost:5433/habit
##    username: postgres
##    password: jiyjo@2001
##    driver-class-name: org.postgresql.Driver
##  jpa:
##    show-sql: true
##    hibernate:
##      ddl-auto: update
##      properties:
##        hibernate:
##          jdbc:
##            lob:
##              non_contextual_creation: true
##        show_sql: true  # Enable Hibernate SQL logging
##        format_sql: true  # Pretty-print the SQL in logs
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/habit
#    username: postgres
#    password: jiyjo@2001
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#
